name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@9230f0db4d54e491221dad48b9d4012b99aaf26b # main
        with:
          repository: openstack/magnum
          ref: e1afb30a755679140289ca0241f2faeed8c71ee6 # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@9230f0db4d54e491221dad48b9d4012b99aaf26b # main
        with:
          image-name: magnum
          build-contexts: magnum=openstack/magnum
          push: ${{ github.event_name != 'pull_request' }}
