name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@01f39b179e76b7da3831bb70bef15e817df49590 # main
        with:
          repository: openstack/magnum
          ref: 7dc17ad7a1d2f85e00f43b0b1de2e648bf083b72 # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@01f39b179e76b7da3831bb70bef15e817df49590 # main
        with:
          image-name: magnum
          build-contexts: magnum=openstack/magnum
          push: ${{ github.event_name != 'pull_request' }}
